### ISSUE TITLE
[logging] log4j2 사용법

### ISSUE THREAD

**Issue by ParkSunJin** [dev-sian/meetings#10]
우리 프로젝트는 멀티쓰레드 환경에서 성능이 가장 좋은 log4j2를 사용할거임

#### 의존성 설정

먼저, spring-boot-starter-web에는 logging 모듈이 추가되어 있는데, spring에서 지원하는 기본 로깅 모듈은 logback이기 때문에 의존성을 제거해야함. (제거하지 않고 log4j2의 의존성을 가져오면 에러남)

```groovy
configurations{
    all{
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }
}
```

그리고 의존성 설정

- 2021년 말에 취약점 이슈가 있었기 때문에 내장된 라이브러리 버전 말고 2.17.0 이상의 버전 사용할거임

```groovy
dependencies {
    // log4j2
    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.17.0'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-slf4j-impl', version: '2.17.0'
    implementation group: 'com.fasterxml.jackson.dataformat', name: 'jackson-dataformat-yaml', version: '2.10.3'
}
```

- jackson-dataformat-yaml 은 log4j2의 설정파일을 yml로 작성하기 위해서

#### application.yml 설정

- 로깅 설정은 log4j2.xml 또는 log4j2.yml을 따로 만들어서 application.yml에서는 이 파일을 참조하도록 설정

```yaml
logging:
  config: classpath:log4j2.xml		 # 또는 log4j2.yml
```

#### log4j2.xml 설정

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">

    <Properties>
        <Property name="logFileName">pyeon-schelin</Property>
        <Property name="consoleLayout">%style{%d{ISO8601}} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%C{1.}}{bright,yellow}: %msg%n%throwable</Property>
        <Property name="fileLayout">%d [%t] %-5level %c(%M:%L) - %m%n</Property>
    </Properties>

    <Appenders>
        <Console name="console" target="SYSTEM_OUT">
            <PatternLayout pattern="${consoleLayout}" disableAnsi="false" />
        </Console>
        <RollingFile name="file" fileName="logs/${logFileName}.log" filePattern="logs/${logFileName}.%d{yyyy-MM-dd-hh}.log">
            <PatternLayout pattern="${fileLayout}" disableAnsi="false"/>
            <Policies>
                <TimeBasedTriggeringPolicy modulate="true" interval="1" /><!-- 시간별 로그 파일 생성-->
            </Policies>
            <DefaultRolloverStrategy max="5" fileIndex="min" /><!-- 롤링 파일 5개 까지 생성 -->
        </RollingFile>
    </Appenders>

    <Loggers>
        <Root level="info" additivity="false">
            <AppenderRef ref="console" level="info"/>
            <AppenderRef ref="file" level="warn"/>
        </Root>

        <!-- 스프링 프레임워크에서 찍는건 level을 info로 설정 -->
        <logger name="org.springframework" level="info" additivity="false" >
            <AppenderRef ref="console" />
            <AppenderRef ref="file" />
        </logger>

        <!-- rolling file에는 debug, console에는 info 분리하여 처리 가능하다. -->
        <logger name="com.devsian" level="debug" additivity="false" >
            <AppenderRef ref="console" level="debug" />
            <AppenderRef ref="file" level="warn" />
        </logger>

    </Loggers>
</Configuration>
```

- Property 태그는 공통적으로 사용하기 위한 속성들을 미리 정의한 것
- Appenders 태그는 로그가 출력되는 위치를 나타낸다
  - 정의한 name은 AppenderRef 태그에서 참조할 때 사용
  - 태그 별 출력 위치
    - Console : 콘솔
    - File : 파일
    - RollingFile : 조건에 따라 롤링(일별, 조건별 등)
      - SizeBasedTriggeringPolicy : 1KB 용량 초과시 DefaultRolloverStrategy 정책 만큼 넘버링
      - TimeBasedTriggeringPolicy : 1일 단위(interval=”1")에 로그파일 새로 생성
      - DefaultRolloverStrategy : 파일 용량 제한 초과시 최대 500개 까지 생성(max=”500")
    - JDBC : DB
  - 실제로 찍혀지는 방법(layout)과 Rolling File 생성에 대한 정책 등을 정의할 수 있다.
- Loggers 태그는 어떤 패키지의 로그에 어떤 Appender를 붙여줄 것인지
  - Root : 일반적인 로그 정책에 대해 정의할 수 있으며, 반드시 한개를 정의해야한다.
  - additivity: 중복로깅여부
  - logger의 level은 logger 하위의 태그들에서 AppenderRef 들의 level limit를 정해줌 (logger 하위의 AppenderRef 의 level이 logger 의 level 보다 높으면 AppenderRef 의 level은 아무 효과가 없음.)

https://huisam.tistory.com/entry/log4j2

#### log4j2.yml(에러나넴ㅎrollingFile 어쩌구 에러남..)

```yaml
Configutation:
  name: Default
  status: warn

  Properties:
    Property:
    - name: logFileName
      value: "pyeon-schelin"
    - name: log-path
      value: "logs"
    - name: consoleLayout
      value: "%style{%d{ISO8601}} %highlight{%-5level }[%style{%t}{bright,blue}] %style{%C{1.}}{bright,yellow}: %msg%n%throwable"
    - name: fileLayout
      value: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

  Appenders:
    Console:
      name: console
      target: SYSTEM_OUT
      PatternLayout:
        pattern: ${consoleLayout}
        disableAnsi: false
    RollingFile:
      - name: file
        fileName: ${log-path}/${logFileName}.log
        PatternLayout:
          pattern: ${fileLayout}
          disableAnsi: false
        Policies:
          SizeBasedTriggeringPolicy:
            size: 1 KB
        DefaultRollOverStrategy:
          max: 5
  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: console
        - ref: file
```

## slf4j 사용법
![image](https://user-images.githubusercontent.com/87985433/167819902-b4f2e88b-6af9-47a9-b319-2bb03b40604e.png)
